spring:
  application:
    name: leafmusic3

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  security:
    user:
      name: ${SPRING_SECURITY_USERNAME}
      password: ${SPRING_SECURITY_PASSWORD}

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  session:
    store-type: none

  jackson:
    serialization:
      write-dates-as-timestamps: false

server:
  address: 0.0.0.0

  servlet:
    context-path: /api
    session:
      timeout: 15m

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD_NAME}
  api_key: ${CLOUDINARY_API_KEY}
  api_secret: ${CLOUDINARY_API_SECRET}