spring.application.name=leafmusic3

spring.datasource.url=jdbc:mysql://localhost:3306/leafmusic
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.security.user.name=admin
spring.security.user.password=admin123

server.servlet.context-path=/api