spring.application.name=leafmusic3

spring.datasource.url=jdbc:mysql://localhost:3306/leafmusic
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.security.user.name=admin
spring.security.user.password=admin123

server.servlet.context-path=/api

jwt.secret=7a2f61c3a2e89e7a6c3b2c3f52d3e5d1bbf86dbd59715ab3e12e572fb18f3c35

jwt.expiration=86400

#=================================================

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

server.servlet.session.timeout=15m
spring.session.store-type=none

#====================================================


spring.jackson.serialization.write-dates-as-timestamps=false


